authorName: Iman Mirzadeh
experimentName: NN-Forget-Perm-NoDropout-Scaled
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 1500

#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_perm.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: Random
trial:
  command: python train.py --hidden_size 256
  codeDir: ..
  gpuNum: 0