authorName: Iman Mirzadeh
experimentName: NN-Forget
trialConcurrency: 2
maxExecDuration: 24h
maxTrialNum: 1500

#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_4.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  command: python train.py --hidden_size 200
  codeDir: ..
  gpuNum: 0